# Copyright (c) 2025
# SPDX-License-Identifier: MIT

---
include:
  - board: xiao_ble//zmk
    shield: cleave_hhjp_left rgbled_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: xiao_ble//zmk
    shield: cleave_hhjp_right rgbled_adapter
  - board: xiao_ble//zmk
    shield: settings_reset
