# Copyright (c) 2025
# SPDX-License-Identifier: MIT

---
include:
  - board: xiao_ble
    shield: cleave_hhjp_left
    snippet: studio-rpc-usb-cdc
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: xiao_ble
    shield: cleave_hhjp_right
